import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "X - clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          userButtonAvatarBox: {
            width: 40,
            height: 40,
          },
        },
      }}
    >
      <html lang="en">
        <body className="bg-black text-white max-w-7xl mx-auto">{children}</body>
      </html>
    </ClerkProvider>
  );
}
