import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "X - clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        elements: {
          userButtonAvatarBox:{
            width: 40,
            height: 40,
          }
        },
      }}
    >
      <html lang="en">
        <body className="bg-black text-white">{children}</body>
      </html>
    </ClerkProvider>
  );
}
